Refactor start-server.yml to remove unnecessary SSH command and add logic to remove existing container before starting a new one

diff --git a/.github/workflows/start-server.yml b/.github/workflows/start-server.yml
--- a/.github/workflows/start-server.yml
+++ b/.github/workflows/start-server.yml
@@ -24,7 +24,11 @@ jobs:
         run: |
           ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_URL << 'ENDSSH'
             echo "Starting the container..."
-           docker run -d -p 8000:8000 --name backend \
+            if [ $(docker ps -aq -f name=backend) ]; then
+              echo "Removing existing container..."
+              docker rm -f backend
+            fi
+            docker run -d -p 8000:8000 --name backend \
               -e MONGO_URL='${{ secrets.MONGO_URL }}' \
               -e PORT='${{ secrets.PORT }}' \
               -e NEXT_PUBLIC_APP_URL='${{ secrets.NEXT_PUBLIC_APP_URL }}' \
@@ -42,5 +46,5 @@ jobs:
               -e AUTH_SECRET='${{ secrets.AUTH_SECRET }}' \
               -e JWT_SALT='${{ secrets.JWT_SALT }}' \
               -e FLASK_BACKEND_ML_URL='${{ secrets.FLASK_BACKEND_ML_URL }}' \
-               ${{ secrets.DOCKER_USERNAME }}/backend:latest || { echo "Docker run failed"; exit 1; }
+              ${{ secrets.DOCKER_USERNAME }}/backend:latest || { echo "Docker run failed"; exit 1; }
           ENDSSH
